services:
  web:
    build: .
    container_name: backend_web
    command: >
      sh -c "python app/manage.py migrate &&
             python app/manage.py collectstatic --noinput &&
             gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --workers 3"
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app # hot-reload de código en dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      timeout: 3s
      retries: 5
