# Generated by Django 5.2.7 on 2025-10-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categoria_created_at_categoria_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='pais_origen',
        ),
    ]
