# Generated by Django 5.2.7 on 2025-10-26 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_marca_pais_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garantia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
