# Generated by Django 5.2.7 on 2025-10-27 16:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_garantia_created_at_garantia_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image_url',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
