# Generated by Django 5.2.7 on 2025-11-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
