# Generated by Django 5.2.7 on 2025-11-06 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaventa',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaventa',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='nota_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.notaventa'),
        ),
        migrations.AlterField(
            model_name='notaventa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=20),
        ),
        migrations.AlterModelTable(
            name='detalle_venta',
            table='sales_detalleventa',
        ),
        migrations.AlterModelTable(
            name='notaventa',
            table='sales_notaventa',
        ),
    ]
